build/nginx/build.sh

Ref https://github.com/omniosorg/omnios-extra/issues/2
built and tested locally.

nginx: update to 1.12.1

---

build/nginx/files/http-nginx.xml

reference master PR: https://github.com/omniosorg/omnios-extra/pull/4

Use ASLR for nginx

---

build/python36/build.sh
build/python36/files/local.mog

reference PR: https://github.com/omniosorg/omnios-extra/pull/12

add mediators to python3 link, major version path

---

build/ooceapps/build.sh
build/ooceapps/files/ooceapps.xml
build/ooceapps/local.mog

adds our mattermost/web integrations to the `extra.omnios` repo so we can easily install/upgrade.

ooceapps added

---

build/pkgmgr/build.sh

we should update pkgmgr for r22 as well, since we need the functionality

pkgmgr: update to version 0.1.11 (r151022)

---

lib/config.sh

initial commit to setup `r151024` branch

getting ready for r151024

---

build/ooceapps/build.sh

see: https://github.com/omniosorg/omnios-extra/pull/48

ooceapps: update to 0.2.2 (r151022)

---

build/ooceapps/build.sh

see: https://github.com/omniosorg/omnios-extra/pull/48

ooceapps: update to 0.2.2 (r151024)

---

build/ooceapps/build.sh

see: https://github.com/omniosorg/omnios-extra/pull/58

ooceapps: update to 0.2.3

---

build/texlive/build.sh
build/texlive/local.mog
build/texlive/patches/series
build/texlive/patches/texmfroot.patch

shipping the full package for now. if we face pkg(5) performance issues we need to rethink.

texlive added

---

build/ooceapps/build.sh
build/ooceapps/local.mog

also restart service automatically on update.

ooceapps: update to 0.2.4

---

build/kvmadm/build.sh
build/lxadm/build.sh

see: https://github.com/omniosorg/omnios-extra/pull/65

kvmadm: update to 0.12.2; lxadm: update to 0.1.6 (r151022)

---

build/kvmadm/build.sh
build/lxadm/build.sh

see: https://github.com/omniosorg/omnios-extra/pull/65

kvmadm: update to 0.12.2; lxadm: update to 0.1.6 (r151024)

---

build/asciidoc/build.sh
build/asciidoc/local.mog
doc/packages.md

AsciiDoc is required to build the man pages for `ntpsec`

Add AsciiDoc to extra

---

build/python36/.gitignore
build/python36/build.sh
build/python36/files/local.mog
build/python36/local.mog
doc/packages.md

```
hadfl@mars:~$ python3 --version
Python 3.6.4
```
additional test: building `iso-codes`

python3: update to 3.6.4

---

build/python36/.gitignore
build/python36/build.sh
build/python36/files/local.mog
build/python36/local.mog

see: https://github.com/omniosorg/omnios-extra/pull/79

python3: update to 3.6.4 (r151022)

---

build/python36/.gitignore
build/python36/build.sh
build/python36/files/local.mog
build/python36/local.mog

see: https://github.com/omniosorg/omnios-extra/pull/79

python3: update to 3.6.4 (r151024)

---

build/pkgmgr/build.sh
doc/packages.md

pkgmgr: update to 0.2.3

---

lib/global-transforms.mog

Reverts omniosorg/omnios-extra#90

Revert "drop 'etc/opt' globally (r151024)"

---

lib/global-transforms.mog

Reverts omniosorg/omnios-extra#89

Revert "drop 'etc/opt' globally (r151022)"

---

build/bdb/build.sh
build/bdb/local.mog
build/kvmadm/build.sh
build/lxadm/build.sh
build/postfix/build.sh
build/postfix/files/smtp-postfix.xml
build/postfix/local.mog
doc/baseline
doc/packages.md

adding postfix

---

lib/functions.sh

see: https://github.com/omniosorg/omnios-build/pull/553

Replace "cannot" with "should not" in places where override is offered

---

build/ccache/build.sh
build/ccache/local.mog
doc/packages.md

Originally from https://github.com/omniosorg/omnios-build/pull/549

 Provide ccache to help speed up code (re-)builds

---

lib/config.sh

release specific IPS_REPO and PERLVER

---

doc/structure.md

I've started a `doc` branch. Let's not merge this until it includes all necessary info so users can start contribute/maintain packages.
Please push your documentation (commits) to this branch. We can squash it when merging.

packages info added

---

build/nodejs/build.sh
build/nodejs/local.mog
doc/baseline
doc/packages.md

Added Node v8.11.2 to Omnios Extras from https://nodejs.org/dist/v8.11.2/node-v8.11.2.tar.gz

Nodejs v8.11.2

---

build/cunit/build.sh
build/cunit/local.mog
doc/packages.md

Needed to properly run nghttp2 regression tests.

Add CUnit Testing Framework

---

lib/config.sh
lib/functions.sh

see: https://github.com/omniosorg/omnios-build/pull/1395

Failing strip or ctfconvert step drops build into loop

---

build/socat/build.sh

see: https://github.com/omniosorg/omnios-build/pull/1507

moved socat to omnios core

---

build/ooceapps/build.sh
build/pkgmgr/build.sh
build/znapzend/build.sh

see: https://github.com/omniosorg/omnios-build/pull/1699

fix perl packages following move to 64-bit-only perl

---

build/ruby/build-27.sh
build/ruby/patches-27/02-config.patch
build/ruby/patches-27/fix_shebang.patch
build/ruby/patches-27/openssl-EAGAIN.patch
build/ruby/patches-27/series
doc/baseline
doc/packages.md

```
hadfl@mars:~$ pkg mediator ruby
MEDIATOR VER. SRC. VERSION IMPL. SRC. IMPLEMENTATION
ruby     system    2.7     system
hadfl@mars:~$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [amd64-solaris2.11]
```

ruby-27 added

---

tools/idlist

```
% ./tools/idlist
group 19 minidlna
group 27 postfix
group 28 postdrop
group 54 unbound
group 55 nsd
group 67 znc
group 79 ooceapps
group 81 nginx
group 82 php
group 85 mattermost
group 86 gitea
group 87 minio
group 90 postgres
user 19 minidlna
user 27 postfix
user 54 unbound
user 55 nsd
user 67 znc
user 79 ooceapps
user 81 nginx
user 82 php
user 85 mattermost
user 86 gitea
user 87 minio
user 90 postgres
```

Add tools/idlist

---

build/ccache/build.sh
build/ccache/local.mog

fixes: https://github.com/omniosorg/omnios-extra/issues/486

ccache: fix broken symlinks

---

lib/functions.sh

Skip "make clean" on first run
Do not count errors from clean

'make clean' errors should not be counted

---

build/bat/build.sh
build/cmake/build.sh
build/gh/build.sh
build/nano/build.sh
build/rclone/build.sh
doc/packages.md

cmake-3.17.3 
nano-4.9.3
rclone-1.52.0
bat-15.4
gh-0.9.0

Extra package updates

---

tools/audit

A tool to quickly check which extra package versions are published to each supported OmniOS release:

Add extra packages auditing tool

---

build/mariadb/build-103.sh
build/mariadb/build-104.sh
build/mariadb/patches-104/05-no-pie.patch
doc/packages.md

`CMakeLists.txt`/`05-no-pie.patch ` will need closer inspection. otherwise, standard update.

Mariadb updates

---

build/apache/build-24.sh
build/nginx/build-118.sh
build/nginx/build.sh
build/nginx/local-mainline.mog
build/nginx/local.mog

`freetype` will also gain brotli support but no changes to the build script were necessary there.

Build extra packages with brotli from r151035

---

build/hyperfine/build.sh
build/hyperfine/local.mog
doc/baseline
doc/packages.md

Same developer as fd and bat, so I just used build.sh from fd.

Add hyperfine

---

build/apache/build-24.sh
build/apr-util/build.sh
build/apr-util/local.mog
build/apr-util/testsuite.log
build/apr/build.sh
build/meta/extra-build-tools.p5m
build/openldap/build.sh
build/openldap/client.mog
build/openldap/files/openldap.xml
build/openldap/local.mog
build/openldap/patches/dnattrfilter.patch
build/openldap/patches/series
build/openldap/server.mog
build/php/build-74.sh
build/php/patches-74/ldap.patch
build/php/patches-74/series
build/postfix/build.sh
build/postfix/local.mog
build/sasl2/build.sh
build/sasl2/patches/configure-ldap.patch
build/sasl2/patches/series
build/zabbix/build.sh
build/zabbix/patches/ldap.patch
build/zabbix/patches/series
doc/baseline
doc/packages.md
lib/functions.sh

and use it in other components

Add openldap

---

build/sg3_utils/build.sh
build/sg3_utils/local.mog
build/sg3_utils/patches/series
build/sg3_utils/patches/solaris.patch
doc/baseline
doc/packages.md

Please add utilities for devices that use SCSI command sets

sg3_utils: add

---

build/isc-bind9/bind.p5m
build/isc-bind9/build-911.sh
build/isc-bind9/files/named-template.xml
build/isc-bind9/files/named.conf-template
build/isc-bind9/files/rfc.zones
build/isc-bind9/local.mog

* changed `/etc/opt/ooce/bind-9.11` to `/etc/opt/ooce/named-9.11`
* changed `/opt/ooce/bind-9.11` to `/opt/ooce/named-9.11`
* permissions changed, `named` only access ( tbd )
* cleanup of `named.conf-template`

bind revision - directory name change - permissions - cleanup

---

build/zabbix/build.sh
doc/packages.md

updated build completes without any complications

zabbix update to 5.0.5

---

build/rclone/build.sh
doc/packages.md

updated build completes without any complications

update rclone 1.53.1 > 1.53.2

---

build/lsof/build.sh
build/lsof/patches/include_limits.patch
build/lsof/patches/series
doc/packages.md

added patch as make was not finding "INT_MAX"

update lsof-4.93.2 > 4.94.0

---

build/go/build-114.sh
build/go/build-115.sh
doc/packages.md

includes fixes to the compiler, runtime, the go command, and the net/http package. See the Go 1.14.15/1.15.8 milestones on the Go issue tracker for details.

go updates

---

build/haproxy/build.sh
build/haproxy/files/haproxy-template.xml
build/haproxy/local.mog
doc/baseline
doc/idlist.md
doc/packages.md

haproxy added

---

build/libuv/build.sh
build/libuv/patches/libs.patch
build/libuv/patches/series
build/libuv/testsuite.log

This needs rebasing once #809 is merged.

Libuv cleanup

---

build/nicstat/build.sh
build/nicstat/local.mog
build/nicstat/patches/003-nicstat.c.patch
build/nicstat/patches/series
doc/baseline
doc/packages.md

I tried to create a build script for `nicstat`.
I manually changed the Makefile since there is no configure script, maybe there is a better way of doing this.

add nicstat utility

---

build/mutt/local.mog
build/mutt/patches/nodoc.patch
build/mutt/patches/series

we don't ship any docs for mutt

---

build/mosquitto/build.sh
build/mosquitto/files/ctf.ignore
build/mosquitto/files/ctf.skip
build/mosquitto/files/mosquitto.xml
build/mosquitto/local.mog
build/mosquitto/patches/linkflags.patch
build/mosquitto/patches/mux_epoll_c.patch
build/mosquitto/patches/series
doc/baseline
doc/idlist.md
doc/licences
doc/packages.md

Mosquitto is a MQTT Broker
It is complaining about an unknown license type, but I also noticed there are a few more of those when you grep for 'license=' and compare them against the pattern file.
Whats the play here? Do I update the pattern file or leave as is?

add mosquitto

---

doc/idlist.md

see: https://github.com/omniosorg/omnios-build/pull/2467

add chrony user/group to idlist

---

build/byobu/build.sh
build/byobu/local.mog
doc/baseline
doc/packages.md

Added byobu to complement tmux

byobu 5.133

---

build/apache/build-24.sh
build/apache/local.mog
build/mariadb/build-103.sh
build/mariadb/build-104.sh
build/mariadb/build-105.sh
build/mariadb/build-106.sh
build/mariadb/mariadb.p5m
build/openldap/build.sh
build/openldap/local.mog
doc/idlist.md
lib/config.sh
lib/functions.sh
lib/mog/global-transforms.mog

See also https://github.com/omniosorg/illumos-omnios/pull/1053

Deliver user/group actions for previous system users

---

build/bdw-gc/build.sh
build/cmake/build.sh
build/radare2/build.sh
build/radare2/patches/capstone4.patch
build/radare2/patches/series
build/virtualbox/build.sh
doc/packages.md

Upstream patch applied for radare2 ( https://github.com/radareorg/radare2/commit/645835794b0013b52042d5762d98d03fcbf250f6#diff-40f918b756651cdbb01fc2320e5fcfba2e291a25dae8ab28eabffd81f84ee27e )

package-updates

---

build/subversion/build.sh

Ship perl bindings with subversion

---

build/fuse/build.sh

see: https://www.illumos.org/issues/14284

fuse: kernel modules should be of type kmod

---

build/rrdtool/build.sh

fixes https://github.com/omniosorg/omnios-extra/issues/1033

rrdtool: fix build with python 3.10

---

build/vaultwarden/build.sh
build/vaultwarden/files/vaultwarden.xml
build/vaultwarden/local.mog
doc/baseline
doc/idlist.md
doc/packages.md
lib/functions.sh

This is a work in progress but I wanted to get more eyes on it sooner than later.
I have a few questions, so I plan to comment directly on this PR to ask them.

vaultwarden: add package (ver 1.24.0)

---

build/cyrus/patches/assert.patch
build/cyrus/patches/series

Temporary local fix for https://github.com/cyrusimap/cyrus-imapd/issues/4123

cyrus-imapd: fix build with perl 5.36

---

build/rlwrap/build.sh
build/rlwrap/local.mog
doc/baseline
doc/packages.md

Adding rlwrap package. 
From README:
"rlwrap is a 'readline wrapper', a small utility that uses the GNU Readline library to allow the editing of keyboard input for any command."
https://github.com/hanslub42/rlwrap

Add rlwrap

---

README.md

Add warning about building on old releases

---

build/nagios/build.sh
build/nagios/patches/series
build/nagios/patches/ssl.patch
lib/config.sh

nagios: Fix buffer overflow in SSL code

---

build/tailscale/build.sh
build/tailscale/files/tailscale.xml
build/tailscale/local.mog
doc/baseline
doc/packages.md

I think this is probably most of what is needed, but I could use some help with testing and fixing any bugs/quirks of the package.
If I start figuring this stuff out, I hope to use it as a stepping stone to packaging wireguard-go and wireguard-tools to further my goal of getting all of this work upstreamed into the appropriate projects.

Tailscale package

---

build/tailscale/build.sh
doc/packages.md

https://github.com/nshalman/tailscale/releases/tag/v1.38.1-sunos

tailscale: update to 1.38.1

---

build/mod_wsgi/build.sh
build/mod_wsgi/local.mog
doc/baseline
doc/packages.md

Add Apache module mod_wsgi for WSGI compliant interface for hosting Python application.

add mod_wsgi

---

build/emacs/build.sh

fixes https://github.com/omniosorg/omnios-extra/issues/1273

emacs: source and pre-compiled files must preserve timestamps

---

build/gitea/build.sh
doc/packages.md

fixes https://github.com/omniosorg/omnios-extra/issues/1304

gitea: update to 1.19.3

---

build/libwebp/build.sh
doc/packages.md

fixes https://github.com/omniosorg/omnios-extra/issues/1340

libwebp: update to 1.3.2

---

build/tailscale/build.sh
doc/packages.md

I don't currently have a convenient place to test this, but I've been slacking on providing PRs for this package whenever I tag new https://github.com/nshalman/tailscale/releases so I figure I should at least try to catch it up from time to time.

tailscale: update to 1.50.0

---

build/clang/build-13.sh
build/clang/build-14.sh
build/clang/build-15.sh
build/clang/build-16.sh
build/clang/build-17.sh

fixes https://github.com/omniosorg/omnios-extra/issues/1352

clang requires gcc runtime libraries

---

build/nginx/files/http-nginx-template

Small change to the method file to load the CONF_FILE set in smf

Make nginx load $CONF_FILE

---

build/gptfdisk/build.sh
build/gptfdisk/local.mog
build/gptfdisk/patches/ncurses.patch
build/gptfdisk/patches/no-icu-libs.patch
build/gptfdisk/patches/series
build/gptfdisk/patches/uuid.patch
doc/baseline
doc/packages.md

Packages up the [GPT fdisk](https://sourceforge.net/projects/gptfdisk/) suite of tools: `gdisk`, `cgdisk`, `sgdisk`, `fixparts`.

Add gptfdisk 1.0.9

---

build/squid/build.sh
build/squid/files/exec_attr
build/squid/files/squid
build/squid/files/squid.xml
build/squid/local.mog
build/squid/patches/ac_squid-util.m4.patch
build/squid/patches/configure.ac.patch
build/squid/patches/series
build/squid/rtime
doc/baseline
doc/idlist.md
doc/packages.md

As announced at FOSSDEM, I am sending my work regarding quid here.

squid: add version 6.7 to extra.omnios

---

build/atuin/build.sh
doc/packages.md

Version 17.0.0 just released: https://github.com/atuinsh/atuin/releases/tag/v17.0.0
I haven't run through a build of this, but I am filing the PR anyways.

Update atuin to v18.1.0

---

build/gitea/build.sh
build/minio-mc/build.sh
build/minio/build.sh
doc/packages.md

First couple of updates while I get familiar with the system again.

Package Updates Extra 20240402

---

build/isc-bind9/files/named.root

B.ROOT-SERVERS.NET. got updated some time ago.

Update bind9 named.root hints file.

---

build/tailscale/build.sh
doc/packages.md

https://github.com/nshalman/tailscale/releases/tag/v1.72.1-sunos

tailscale: update to 1.72.1

---

build/meta/extra-build-tools.p5m
build/pg_extension/common.sh
build/postgresql/build-17.sh
build/postgresql/patches-17/dism.patch
build/postgresql/patches-17/pam-illumos.patch
build/postgresql/patches-17/perl_plpgsql.patch
build/postgresql/patches-17/series
doc/baseline
doc/packages.md

This is the initial attempt to compile postgresql 17 but for now it doesn't. First of all because of a warning/error in some perl pgsql stuff for which I found a workaround by some googling around. But still it fails and I must be somewhat blind to see why the make fails.

Add postgresql 17

---

build/tailscale/build.sh
doc/packages.md

https://github.com/nshalman/tailscale/releases/tag/v1.76.3-sunos

tailscale: update to 1.76.3

---

build/atuin/build.sh
doc/packages.md

Bump atuin to 18.4.0

---

build/alpine/patches/autoreconf.patch
build/alpine/patches/lib.patch
build/alpine/patches/series
build/alpine/patches/uuid.patch
lib/functions.sh

fixes https://github.com/omniosorg/omnios-extra/issues/1578.

add runtime linker option to pkg-config files

---

build/zig/build-0.14.sh
build/zig/patches-0.14/add-arc4random_buf.patch
build/zig/patches-0.14/fix-watch-init.patch
build/zig/patches-0.14/interp-check.patch
build/zig/patches-0.14/is-valid-memory.patch
build/zig/patches-0.14/keep-frame-pointers.patch
build/zig/patches-0.14/patch-getCpuCount.patch
build/zig/patches-0.14/series
build/zig/patches-0.14/stack-trace-thread-safety.patch
build/zig/patches-0.14/verbose-link.patch
doc/baseline
doc/packages.md

There's some issue with threadlocal storage, but I don't think it needs to hold up the package given zig's quickly evolving nature. I might look into it more in the coming weeks and perhaps a follow-up patch could be done.

add zig-0.14.0

---

build/caddy/build.sh
doc/packages.md

This is my first pull, please let me know if anything missing.
It builds and *seems* to run.

Caddy: update to 2.10.0

---

build/meta/extra-build-tools.p5m
build/victoriametrics/build.sh
build/victoriametrics/files/vmagent-profile.xml
doc/packages.md

Fix vmagent profile service name.
Upgrade to go 1.24

Update VictoriaMetrics to v1.117.1

---

build/helix/build.sh
doc/packages.md

Bump to the new release of Helix. I built, installed, and tested on my own system, and it all looks good.

Helix: update to 25.07.01

---

build/vaultwarden/build.sh
doc/packages.md

This bumps the vaultwarden and bundled web vault.
EDIT:
```
--- Publishing package to file:///ws/omnios-extra/tmp.repo/
Intentional pause: Last chance to sanity-check before publication!
Do you wish to continue anyway? (y/n) y
===== User elected to continue after prompt. =====
--- Published ooce/application/vaultwarden@1.34.3,5.11-151054.0
--- Comparing old package with new
-set name=info.source-url.0 value=https://github.com/dani-garcia/vaultwarden/tree/1.34.1
+set name=info.source-url.0 value=https://github.com/dani-garcia/vaultwarden/tree/1.34.3
-set name=info.source-url.2 value=https://github.com/dani-garcia/bw_web_builds/releases/download/v2025.5.0/bw_web_v2025.5.0.tar.gz
+set name=info.source-url.2 value=https://github.com/dani-garcia/bw_web_builds/releases/download/v2025.7.0/bw_web_ …
```

Bump vaultwarden to 1.34.3 and web vault to 2025.7
