omniosorg/omnios-extra

build/nginx/files/http-nginx.xml

We can easily run nginx with address-space layout randomisation by adding a security flag to the start method context. Is this something we should enable in the extra package by default?
```
bloody# psecflags `pgrep -o nginx`
2496:   /opt/ooce/sbin/nginx
E:      aslr
I:      aslr
L:      none
U:      aslr,forbidnullmap,noexecstack
```

Use ASLR for nginx?

---

build/apache-ant/build.sh
build/apache-ant/local.mog
build/freetype2/build.sh
build/freetype2/local.mog
build/python36/.gitignore
build/python36/build.sh
build/python36/files/local.mog
build/python36/patches/cgi.py.patch
build/python36/patches/series

to satisfy build dependencies for `iso-codes` and `openjdk`

apache-ant, freetype and python-36 for r151022

---

build/python36/build.sh
build/python36/files/local.mog

Replaces https://github.com/omniosorg/omnios-extra/pull/11
This change makes the symlink to python (`/opt/ooce/bin/python3`) into a mediated link, allowing multiple omnios-extra versions of python3 to be installed in parallel, should the need arise.
Install directories are named after the major version. e.g. `/opt/ooce/python-3.6`
```
bloody# pkg mediator -a
MEDIATOR VER. SRC. VERSION IMPL. SRC. IMPLEMENTATION
gcc      system    5.1     system
mta      system            system     mailwrapper
mta      system            system     sendmail
python3  system    3.6     system
```

add mediators to python3 link, major version path

---

build/ooceapps/build.sh

also moving releases for `ooceapps` from `hadfl` to `omniosorg`

ooceapps: update to 0.2.2

---

build/irssi/build.sh
build/irssi/local.mog
build/znc/build.sh
doc/packages.md
lib/config.sh
lib/functions.sh

Adding irssi.
Changing config.sh to automatically detect the release of the build host and create packages with that release version. At present the only difference between the release branches is this setting and this will allow us to remove the r151022/24 branches and maintain everything in one place.

Add irssi package + support for building all releases from master

---

build/docbook/build.sh
build/docbook/local.mog
build/docbook/patches/series
build/docbook/patches/sourceforge.patch

This provides local copies of stylesheets that can be used when generating man pages using asciidoc instead of retrieving them from sourceforge.net

docbook: add docbook xsl package

---

build/php/build-72.sh
build/php/files/php-72
build/php/files/php72.xml
build/php/local.mog
build/php/patches-72/configure.patch
build/php/patches-72/series
doc/packages.md

The service will run straight out of the box and listen on a UNIX socket with `svcadm enable php72`- configuration can be modified in `/etc/opt/ooce/php-7.2/php-fpm.d/` as desired - to alter the number of instances, configure additional pools, etc.
Adding something like the following block to the nginx configuration enables handling of PHP scripts via the FPM server.
```
location ~ \.php$ {
try_files $uri =404;
fastcgi_pass unix:/var/opt/ooce/php/run/www.sock;
fastcgi_index index.php;
include fastcgi.conf;
}
```
A fairly minimal set of PHP modules is enabled for this release - those for which extra dependencies are not required - more can be added in future.

Add PHP 7.2 package with FPM service

---

build/smartmontools/build.sh
build/smartmontools/patches/bash-shebang.patch
build/smartmontools/patches/series

The update-smart-drivedb script uses some bash extensions but has /bin/sh in the shebang line. It also uses a path that excludes /opt/ooce/bin which means that it cannot find the gpg utility.

Fix smartmontools update-smart-drivedb script

---

build/virtualbox/build.sh
build/virtualbox/local.mog

This, along with the other PRs to add source-URLs, results in these package differences:
```diff
--- Published ooce/virtualization/virtualbox@5.2.22,5.11-151028.0
--- Comparing old package with new
+set name=info.source-url.0 \
+    value=https://mirrors.omniosce.org/gsoap/gsoap_2.8.73.zip
+set name=info.source-url.1 \
+    value=https://mirrors.omniosce.org/VirtualBox/VirtualBox-5.2.22.tar.bz2
+license 1d0fe189cc6789d7d16c8ac9a84e56e7fcd9f530 license=GPLv2
```

Virtualbox: add gsoap licence

---

build/nsd/build.sh
build/unbound/build.sh

Following the recent fix to the openssl header symlink.

nsd/unbound can build with openssl 1.1

---

build/libvncserver/build.sh
doc/packages.md

The last published version if 0.9.11 but we package the github master from 20181116. The version number should be such that when 0.9.12 is released then it is greater than the version we ship.

Adjust libvncserver version

---

build/ruby/patches-26/openssl-EAGAIN.patch
build/ruby/patches-26/series
lib/functions.sh

Ruby 2.6 performs parallel downloads when installing gems, and this exposes a fault in the ruby openssl module where it does not handle EAGAIN coming back from a non-blocking SSL_read() call. The OpenSSL documentation suggests that EAGAIN should not be a response that comes back from SSL_read(), although the interface allows for arbitrary errnos to come back from the underlying OS.
In any case, EAGAIN means that the operation should be retried.
With this patch in place:
```
% ls -l =gem
lrwxrwxrwx   1 root     root          19 Jan 22 21:50 /opt/ooce/bin/gem -> ../ruby-2.6/bin/gem*
% pfexec gem install bundler
Fetching bundler-2.0.1.gem
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Installing ri documentation for bundler-2.0.1
Done installing documentation …
```

Ruby 2.6, fix gem install

---

build/bat/build.sh
build/bat/local.mog
build/bat/patches/Cargo.toml.patch
build/bat/patches/series
build/fd/build.sh
build/fd/local.mog
build/fd/patches/Cargo.toml.patch
build/fd/patches/series
doc/licences
doc/packages.md

With many thanks to @papertigers for the assistance in building these, and for the work he is doing to add illumos support to rust crates.

Add rust 'fd' and 'bat' utilities.

---

build/openvpn/local.mog

Fixes:
```
FMRI pattern might implicitly match more than one service instance.
Actuators for restart_fmri will not be run for svc:/ooce/network/openvpn.
```

Add explicit restart FMRI targets

---

build/cmake/build.sh
build/libpng/build.sh
doc/packages.md

`libpng`: fixing [CVE-2019-7317](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-7317)

package updates

---

build/lz4/build.sh
build/lz4/patches/Makefile.patch
build/lz4/patches/series
doc/packages.md

> This is a point release, which main objective is to fix a read out-of-bound issue reported in the decoder of v1.9.0. Upgrade from this version is recommended.

lz4: update to 1.9.1

---

build/virtualbox/vbox.mog

Reported by @jimklimov
This change adds these lines to the final manifest:
```
link path=opt/VirtualBox/VBoxManage target=amd64/VBoxManage
link path=opt/VirtualBox/VBoxBugReport target=amd64/VBoxBugReport
link path=opt/VirtualBox/VBoxBalloonCtrl target=amd64/VBoxBalloonCtrl
link path=opt/VirtualBox/VBoxZoneAccess target=amd64/VBoxZoneAccess
link path=opt/VirtualBox/VBoxXPCOMIPCD target=amd64/VBoxXPCOMIPCD
link path=opt/VirtualBox/VBoxDTrace target=amd64/VBoxDTrace
link path=opt/VirtualBox/VBoxSVC target=amd64/VBoxSVC
link path=opt/VirtualBox/VBoxAutostart target=amd64/VBoxAutostart
link path=opt/VirtualBox/VBoxExtPackHelperApp target=amd64/VBoxExtPackHelperApp 
```

Add missing binary links

---

build/virtualbox/patches/build-in-zone.patch
build/virtualbox/patches/configure.patch
build/virtualbox/patches/ctf.patch
build/virtualbox/patches/hma.patch
build/virtualbox/patches/series
build/virtualbox/patches/solaris-install.patch
build/virtualbox/patches/stackclash.patch

```
theeo% ctfdump -c /platform/i86pc/kernel/drv/amd64/vboxdrv
ctfdump: failed to open file /platform/i86pc/kernel/drv/amd64/vboxdrv: File does not contain CTF data
```
```
theeo% pfexec pkg apply-hot-fix https://hf.omnios.org/r151030/vbox6-ctf.p5p
theeo% pfexec init 6
...
theeo% ctfdump -c /platform/i86pc/kernel/drv/amd64/vboxdrv | more
/* Types */
typedef struct { /* 0x2 bytes */
union  class_u; /* offset: 0 bytes */
} Classification_t;
typedef struct { /* 0x20 bytes */
uint32_t c1; /* offset: 0 bytes */
uint32_t c2; /* offset: 4 bytes */
uint32_t c3; /* offset: 8 bytes */
uint32_t c4; /* offset: 12 bytes */
uint32_t c5; /* offset: 16 bytes */
uint32_t c6; /* offset: 20 bytes */
uint32_t c7; /* offset: 24 bytes */
uint32_t c8; /* offset: 28 bytes */
} Compartments_t;
... (etc.)
```

Virtualbox should include CTF data

---

build/top/patches/10.zfs_compressed_arc.patch

From OpenIndiana - thanks @pyhalov

11655 top(1) computes compressed ARC ratio incorrectly

---

build/protobuf/build.sh
build/protobuf/local.mog
lib/functions.sh

Protobuf currently includes a literal `/$(ORIGIN)/` directory:
```
PATH
$(OPREFIX)/bin/amd64/protoc
$(OPREFIX)/bin/i386/protoc
$(OPREFIX)/bin/protoc
...
```

Fix protobuf package

---

build/php/build-74.sh

Helpfully, `--with-gd` has become `--enable-gd`

PHP 7.4 was missing the GD module

---

build/mariadb/build-104.sh
build/mariadb/files/README.install
build/mariadb/files/mariadb-104
build/mariadb/files/mariadb-104.xml
build/mariadb/patches-104/04-dtrace.patch
build/mariadb/patches-104/05-no-pie.patch
build/mariadb/patches-104/08-dtrace-invalid-conversion.patch
build/mariadb/patches-104/auth_socket.diff
build/mariadb/patches-104/series
build/mariadb/patches-104/si_kernel.patch
lib/config.sh
lib/functions.sh

Automatically create an initial database on first start.
Fix and enable UNIX socket authentication.
Enable dtrace support.
Use system zlib (previously the bundled version was used)
Move items from scripts/ to bin/
Show release notes during installation
See https://omnios.org/article/mariadb

mariadb-104: various improvements

---

build/meta/extra-build-tools.p5m
build/vagrant/build.sh
build/vagrant/local.mog
build/vagrant/patches/series
build/vagrant/patches/vagrant-installers-main-go.patch
doc/baseline
doc/packages.md
lib/functions.sh

Build and distribute virtualized development environments
Initial version of Vagrant for OmniOSce. Mostly based on the same setup
used on Arch Linux with embedded gems and the go based vagrant binary
wrapper.

Provide Vagrant for OmniOSce

---

build/tree/build.sh
build/tree/local.mog
build/tree/patches/Makefile.patch
build/tree/patches/series
doc/baseline
doc/packages.md

Tree is a recursive directory listing command that produces a depth indented listing of files, which is colorized ala dircolors if the LS_COLORS environment variable is set and output is to tty. 
Tree has been ported and reported to work under the following operating systems: Linux, FreeBSD, OS X, Solaris, HP/UX, Cygwin, HP Nonstop and OS/2.  And if all this looks good, now for OmniOSce.

add tree-1.8.0 build files

---

build/nagios/build.sh
build/nagios/files/README.install
build/nagios/files/README.md
build/nagios/files/application-nagios
build/nagios/files/nagios-nginx-example.conf
build/nagios/files/nagios.xml
build/nagios/local.mog
build/nagios/patches/sample-files.patch
build/nagios/patches/series
doc/baseline
doc/packages.md

tarball info:
tarball: https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-4.4.5/nagios-4.4.5.tar.gz
( sha256 bf69e2d2fae218694585677472d355ba676120cbd024164281e635dc467c391d )
extracts to nagios-4.4.5
build info:
pkg install git gcc8 gnu-make ripgrep pigz gnu-tar autoconf automake libtool pkg-config
notes in local.mog
1. only made bin symlinks, so as not to fill up sbin with lots of cgi files
2. changed lots of permissions as this is how nagios normally installs, I kept /opt/ooce/nagios as root bin but had to change these nagios binaries to 755 as they are normally set 744
3. also created group nagcmd as is normal in nagios installation
4. used uid/gid of 120/1 ,as it is pretty crowded in the 90's with system uid's
notes on build.sh
1. MAKE_INSTALL_ARGS: nagios will …

add nagios-4.4.5 build files

---

build/nagios-plugins/build.sh
build/nagios-plugins/final.mog
build/nagios-plugins/local.mog
build/nagios-plugins/patches/check_dhcp.c.patch
build/nagios-plugins/patches/pst3.c.patch
build/nagios-plugins/patches/series
doc/baseline
doc/packages.md

tarball: http://www.nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
( sha256 07859071632ded58c5135d613438137022232da75f8bdc1687f3f75da2fe597f )
extracts to nagios-plugins-2.3.3
notes on build.sh
1. RUN_DEPENDS_IPS: was not sure how to make build dependent packages optional for run_depends. looking under functions.sh I saw it possibe to "case" with variable symbols as the first character. 
however, this did not remove the original "required" dependency so I added the following line in my functions.sh to drop the required package in the final.mog
```
#functions.sh - lines 1318-1320
if grep -q "^depend .*fmri=[^ ]*$depname" "${P5M_INT3}.res"; then
+                logcmd sed -i "\%^depend .*fmri=[^ ]*$depname%d" ${P5M_INT3}.res
autoresolved=true
```
without this the build will have …

add nagios-plugins-2.3.3 build files

---

build/nagios/nagios-common.p5m
doc/baseline

Hi Andy, Dominik,
I hope this looks good. the only things I should mention asides from moving the nagios user and directory structure to the nagios-common skeleton package is:
1. nagios seems to alter the licences for markdown, so I have made simple patches in nrdp, nrpe and nsca to modify this so the license tool can recognize the license.
2. I did not add nagios-common to packages.md as I did not see other similar packages such as nginx,postgres-common listed in this file.
cheers, 
Philip

add nagios-common package

---

build/sysstat/patches/config.patch
build/sysstat/patches/series

The configure script executes two branches. In one, the getopts parameters string doesn't contain -n, thus triggering an error when "configure -n" is called.

sysstat: Add -n option in configure ksh script to prevent build error

---

build/nginx/build-116.sh
build/nginx/build-118.sh
build/nginx/build.sh

The file nginx.8 in $TMPDIR/$BUILDDIR/man is a template containing %% parameters to be substituted with the correct values during build.  The generated file nginx.8 is in $TMPDIR/$BUILDDIR/objs.

nginx: want proper paths in nginx.8

---

build/gyp/build.sh
build/gyp/local.mog
doc/baseline

This is a pre-requisite for switching Mozilla nss/nspr to the new build system.

Add gyp (generate your projects)

---

README.md

This is almost done, I have a little work to do on the "specific packages" section but thought it would be a good time to get it up now.
In the package example section, I created a helloworld source tarball that builds under OmniOS and think it will be less confusing to use that as the example. I have used `set_mirror` in the `build.sh` to download the source but I think it would be better if we could remove this, so that we have a clean `build.sh` template in the document. Though, that would mean the helloworld source tarball would need to go on the omniosce mirror, if that is OK.
Let me know what you think,
Philip

packaging README.md

---

build/acltool/build.sh
build/acltool/local.mog
doc/baseline
doc/packages.md

New package/program - acltool, a cli tool to manage NFSv4/ZFS ACLs in various ways on Solaris/OmniOS, FreeBSD, Linux & MacOS in a uniform way.

acltool version 1.16.2

---

build/acltool/rtime
lib/functions.sh

This patch adds support for package-local "rtime" files to override/add exceptions defined in "doc/rtime" file on a per-package basis. This can be useful if a package has special needs.
One such example is libreadline which must be linked with either libtermcap, libcurses or libncurses - but neither one of then is referenced by libreadline - so the check_rtime tool will always complain about libtermcap/libcurses/libncurses been unneeded. With this patch one can add a local "rtime" file in the package directory like this:
```
UNREF_OBJ libtermcap\.so\.1
UNREF_OBJ libcurses\.so\.1
UNREF_OBJ libncurses\.so\.6
```

Enable package-local rtime file for overrides

---

doc/idlist.md

This brings together all allocated uids and gids from illumos-omnios, omnios-build and omnios-extra.
Since most new UIDs will be allocated for the extra repository, it is most at home here.

Add consolidated uid/gid list

---

build/postgresql/build-10.sh
build/postgresql/build-11.sh
build/postgresql/build-12.sh
build/postgresql/build-96.sh
doc/packages.md

These build fine and the differences in the pkg diffs seem to be just timezone related.
diffs can be found here:
[pbdigital.org/pkgdiffs/postgresql-10.14.txt](https://pbdigital.org/pkgdiffs/postgresql-10.14.txt)
[pbdigital.org/pkgdiffs/postgresql-11.9.txt](https://pbdigital.org/pkgdiffs/postgresql-11.9.txt)
[pbdigital.org/pkgdiffs/postgresql-12.4.txt](https://pbdigital.org/pkgdiffs/postgresql-12.4.txt)
[pbdigital.org/pkgdiffs/postgresql-9.6.19.txt](https://pbdigital.org/pkgdiffs/postgresql-9.6.19.txt)

postgresql updates

---

build/cyrus/patches/memrchr.patch
build/cyrus/patches/timespec.patch

Since the cyrus work, I've opened a couple of upstream PRs against cyrus-imapd.
This is to replace the previous local patches with the versions that are hopefully going upstream.

cyrus: Replace patches with upstream PR version

---

build/postfix/build.sh

Given we now depend on cyrus sasl libs which depends on mariadb and PostgreSQL this change is low hanging fruit that
has little impact on the postfix package. The only changes are:
+depend type=require fmri=pkg:/ooce/library/mariadb-104
+depend type=require fmri=pkg:/ooce/library/postgresql-12
for the newly published package. I myself don't use mysql or postgresql tables in my postfix installs but people might
and we can give them what they want for no additional costs other than these small build changes.

Build postfix with sqlite3, mariadb and postgresql support

---

build/buildctl
build/mariadb/build-104.sh
build/mariadb/build-105.sh
build/subversion/build.sh
build/zabbix/build.sh
tools/audit
tools/test

```
build:omnios-extra:split% ./buildctl list > new
build:omnios-extra:split% git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
build:omnios-extra:master% yes | ./buildctl list > old
--- old 2020-09-17 19:22:09.947301641 +0000
+++ new 2020-09-17 19:19:01.039124478 +0000
@@ -1,10 +1,4 @@
- * ${PKG/database/library}
- * ${PKG/network/library}
* ooce/application/fcgiwrap
* ooce/application/gitea
* ooce/application/gnuplot
@@ -142,7 +136,6 @@
* ooce/runtime/ruby-27
* ooce/runtime/tcl
* ooce/security/gnupg
- * ooce/server/apache-$sAPACHEVER/modules/subversion
* ooce/server/apache-24
* ooce/server/nginx
* ooce/server/nginx-118
```

Fix package name extraction

---

build/imagemagick/build.sh
build/imagemagick/local.mog
build/meta/extra-build-tools.p5m
doc/packages.md
tools/test

Adding HEIC image and webp compression support for imagemagick.
HEIC is a format used by default on images taken with recent IOS versions

Add HEIC support to ImageMagick

---

build/lxadm/build.sh
doc/baseline
doc/packages.md

stop building lxadm which has been superseded by zadm

---

build/mariadb/server.mog
build/postgresql/server.mog

This is necessary because otherwise installing just the library package from a higher version changes the mediator. The mediator should only be changed automatically by server packages.

set mediator-priority to vendor for server packages

---

build/meta/extra-build-tools.p5m
build/php-imagick/build.sh
build/php-imagick/local.mog
build/php-imagick/patches/amd64.patch
build/php-imagick/patches/series
doc/packages.md
tools/audit

Tested that audit picks up PHP versions correctly
```
hawkeye% ./tools/audit -f -p php
Package                                Version          bloody         r151034         r151032         r151030
-------                                -------          ------         -------         -------         -------
application/php-72                      7.2.33          7.2.33          7.2.33          7.2.33          7.2.33
application/php-73                      7.3.22          7.3.22          7.3.22          7.3.22          7.3.22
application/php-73/imagick               3.4.4              --              --              --              --
application/php-74                      7.4.10          7.4.10          7.4.10          7.4.10          7.4.10
application/php-74/imagick               3.4.4 …
```

add imagick php extension

---

build/isc-bind9/build-911.sh
doc/packages.md

--- 9.11.24 released ---
5516.	[func]		The default EDNS buffer size has been changed from 4096
to 1232 bytes. [GL #2183]
5513.	[doc]		The ARM section describing the "rrset-order" statement
was rewritten to make it unambiguous and up-to-date with
the source code. [GL #2139]
5510.	[bug]		Implement the attach/detach semantics for dns_message_t
to fix a data race in accessing an already-destroyed
fctx->rmessage. [GL #2124]
5506.	[bug]		Properly handle failed sysconf() calls, so we don't
report invalid memory size. [GL #2166]
* update installed and tested using dig

update isc-bind 9.11.23 > 9.11.24

---

build/imagemagick/build.sh
doc/packages.md

sub libraries not updated as they are still current
`testsuite.log` output is same as previous version

ImageMagick update to 7.0.10-34

---

build/mattermost/build.sh
build/mattermost/patches-mattermost-server/release.mk.patch
doc/packages.md

updated build completes without any complications, after updating `release.mk.patch`.

mattermost 5.28.0 > 5.28.1

---

build/openvpn/build.sh
build/openvpn/patches/manpage.patch
build/openvpn/patches/series

Regression in 2.5.0 that caused the `openvpn.8` man page not to be installed if `python-docutils` was not installed on the system.
This has been reported upstream and the included patch has been supplied by OpenVPN developers. 
I have tested build on OmniOS and this completes successfully.
However I had to add `run_autoreconf -i` to `build.sh` as `make` failed with:
```
...
configure.ac:59: error: version mismatch.  This is Automake 1.16.2,
configure.ac:59: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:59: comes from Automake 1.16.1.  You should recreate
configure.ac:59: aclocal.m4 with aclocal and run automake again.
WARNING: 'automake-1.16' is probably too old.
...
```
OpenVPN Mailing List message:
https://sourceforge.net/p/openvpn/mailman/message/37140022/

OpenVPN - Fix missing install of man page

---

build/php/build-74.sh

Requested by OmniOS user ( https://illumos.topicbox.com/groups/omnios-discuss/T64335220c445c7bf-Mf5c08bc1cf2cccadd67cd45e/php74-pdo-pgsql ) and since we already include postgres support, it's a simple addition.
With this change, phpinfo output includes:
```
pdo_pgsql
PDO Driver for PostgreSQL => enabled
PostgreSQL(libpq) Version => 12.4
pgsql
PostgreSQL Support => enabled
PostgreSQL(libpq) Version => 12.4
PostgreSQL(libpq)  => PostgreSQL 12.4 on x86_64-pc-solaris2.11, compiled by gcc (OmniOS 151036/10.2.0-il-0) 10.2.0, 64-bit
Multibyte character support => enabled
SSL support => enabled
Active Persistent Links => 0
Active Links => 0
```

Include pdo-pgsql support in PHP 7.4

---

build/libjpeg-turbo/build.sh
build/protobuf/build.sh
doc/packages.md

Regards `protobuf` library, there is an ABI change, as follows:
`libprotoc ABI change, 24  -> 25 `
It looks like just `mosh` that uses `protobuf`, therefore I have built `mosh` with new `protobuf` and the build completes without errors.

Library updates

---

build/gnu-smalltalk/build.sh
build/gnu-smalltalk/local.mog
build/gnu-smalltalk/patches/01-environ.patch
build/gnu-smalltalk/patches/02-emacs.patch
build/gnu-smalltalk/patches/03-relative-symlink.patch
build/gnu-smalltalk/patches/series
build/gnu-smalltalk/testsuite.log
build/meta/extra-build-tools.p5m
doc/baseline
doc/packages.md

This package was originally written by Steve Byrne who was a Sun employee I think, longtime ago ...
I can build it in the omnios-extra and it installs ok for me in the https://pkg.omniosce.org/r151036/extra/
Please note that there are some issues where I just type "yes" when it asks "do you want to continue" ?
For example,
1) unused object=/lib/libpthread.so.1      <remove lib or -zignore?>
ELF runtime problems detected
2) -- Checking for library ABI changes
Could not retrieve contents
3) These hardlinks do not have locked targets, resulting in inconsistent builds.
--- Unlocked hardlink: opt/ooce/bin/gst-load <- opt/ooce/bin/gst-blox
However when I just go ahead
===== User elected to continue after prompt. =====
Then it stilll seems to build fine and install OK for me.
When I manually …

gnu-st: GNU smalltalk 3.2.5

---

build/sasl2/build.sh
build/sasl2/patches/ldapdb-quieter.patch
build/sasl2/patches/series
build/sasl2/patches/sql-quieter.patch

Make auxprop sql plugin even quieter so the plugin init doesn't log anything to auth.error syslog facility when not configured.
Added auxprop ldapdb plugin which is available but was not compiled only ldap support for saslauthd was enabled. This plugin also
needed some coding to make it silent. e.g. it should return SASL_NOMECH just as sql plugin does when not configured and needed to add extra check in sasl_canonuser_add_plugin() so its silent when SASL_NOMECH is returned from an init function.

Cyrus SASL fixes

---

build/apache/build-24.sh
build/cyrus/build.sh
build/cyrus/local.mog
build/jansson/build.sh
build/jansson/local.mog
build/meta/extra-build-tools.p5m
doc/baseline
doc/packages.md

https://httpd.apache.org/docs/2.4/mod/mod_md.html
This is pretty nice when grabbing your certificates via letsencrypt or another acme compatible CA.
@citrus-it this is the thing I was blabbering about on IRC.
I'm not super excited about having it pull in libjansson and curl as dependencies though. I there an easy way to split mod_md off to a separate package? Or would that be more work than it's worth?

Build mod_md for apache-24

---

build/apache/files/apache-template.xml

I noticed apache wasn't properly stopping,
```
root@docs:/opt/httpd/logs# svcs apache24
STATE          STIME    FMRI
online         11:15:24 svc:/network/http:apache24
root@docs:/opt/httpd/logs# svcadm disable apache24
root@docs:/opt/httpd/logs# svcs apache24
STATE          STIME    FMRI
online*        11:15:49 svc:/network/http:apache24
root@docs:/opt/httpd/logs# pgrep httpd
13021
13020
13018
13019
root@docs:/opt/httpd/logs# tail -n 25 $(svcs -L apache24)
[ May 17 14:33:48 Disabled. ]
[ May 17 14:33:48 Rereading configuration. ]
[ May 17 14:35:36 Rereading configuration. ]
[ May 25 21:21:23 Disabled. ]
[ May 29 10:42:35 Enabled. ]
[ May 29 10:42:35 Executing start method ("/opt/ooce/apache-2.4/bin/apachectl -k start -f \'/opt/httpd/conf/httpd.conf\'"). ]
httpd: Could not open …
```

apache fails to stop properly due to missing privilages

---

build/virtualbox/patches/build-in-zone.patch
build/virtualbox/patches/ctf.patch
build/virtualbox/patches/installctx.diff
build/virtualbox/patches/series
build/virtualbox/patches/solaris-install.patch

Tested that this updated virtualbox package works on r151038 both before and after illumos 13915.
```
theeo% uname -a
SunOS theeo 5.11 omnios-r151038-a4c5b5181d i86pc i386 i86pc   <- upcoming r151038k
theeo% vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
theeo% vagrant ssh
Linux debian-10 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
Last login: Sat May  1 20:07:19 2021 from 10.0.2.2
vagrant@debian-10:~$
```

Update Virtualbox to support illumos 13915

---

build/freeradius/build.sh
build/freeradius/files/README.server-install
build/freeradius/files/freeradius-template.xml
build/freeradius/local.mog
doc/baseline
doc/idlist.md
doc/packages.md

This adds freeradius 3.0, and libtalloc as this is a dependency we do not have.
The svc methode will copy the example config if no user config is provided, as sometimes you delete files from the example config, we don't want an update/upgrade to put them back.
```
root@build:~# ls -l /etc/opt/ooce/freeradius-3.0/
total 0
root@build:~# svcadm enable freeradius
root@build:~# ls -l /etc/opt/ooce/freeradius-3.0/
total 19
-rw-r--r--   1 radius   radius     20807 Jun 19 19:35 README.rst
drwxr-xr-x   2 radius   radius        36 Jun 19 19:35 certs
-rw-r--r--   1 radius   radius      8323 Jun 19 19:35 clients.conf
-rw-r--r--   1 radius   radius      1440 Jun 19 19:35 dictionary
-rw-r--r--   1 radius   radius      2661 Jun 19 19:35 experimental.conf
lrwxrwxrwx   1 radius   radius        30 Jun 19 …
```

freeradius 3.0

---

build/mosquitto/build.sh
build/mosquitto/files/mosquitto.xml

mosquitto.xml now uses variables to not have hardcoded things like USER/GROUP and actually specifies the config path again, I'm pretty sure I had it in there originally but I guess not.
This slipped through the testing I did as the only change i had was toggle persistence in my config. Which wasn't picked up as I didn't do my testing cross mosquitto restarts.

Actually have mosquitto use the config file

---

build/gnu-smalltalk/patches/04-filearg.patch
build/gnu-smalltalk/patches/series

This patch was submitted by Tino Calancha (I think of SUSE.de) for GNU smalltalk 3.2.91.
It is very simple but important, this is a backport to 3.2.5
I appreciate the inclusion of GNU smalltalk (originally written by a SunSoft engineer) in Om,niOS CE !

Tino patch

---

build/byobu/build.sh
build/byobu/patches/read_ctrl-a.in.patch
build/byobu/patches/series

I was having trouble were the interactive usage of byobu-ctrl-a would fail. Switched from head to read -p to resolve the issue.

Fixed user input bug by switching to read

---

build/freeradius/build.sh

On a new install I noticed the default radiusd.conf has `//` in 2 places, not a big deal. 
But we can easily fix this by bringing `--with-logdir=` and `--localstatedir=` inline with how they are setup for `--sysconfdir=`. 
This results in the following change in radiusd.conf
```diff
--- a/freeradius/etc/radiusd.conf
+++ b/freeradius/etc/radiusd.conf
@@ -1,9 +1,9 @@
prefix = /opt/ooce/freeradius
exec_prefix = ${prefix}
sysconfdir = /etc/opt/ooce/freeradius
-localstatedir = /var//opt/ooce/freeradius
+localstatedir = /var/opt/ooce/freeradius
sbindir = /opt/ooce/freeradius/sbin
-logdir = /var/log//opt/ooce/freeradius
+logdir = /var/log/opt/ooce/freeradius
raddbdir = /etc/opt/ooce/freeradius
radacctdir = ${logdir}/radacct
```

Cleanup double / in default radiusd.conf

---

build/mariadb/build-104.sh
build/mariadb/build-105.sh
build/mariadb/build-106.sh

and not the library/mariadb-* packages

mariadb-common is only required by database/mariadb-*

---

build/gnupg/build.sh
build/gnupg/files/exec_attr
build/gnupg/local.mog

This fixes the `gpg: Warning: using insecure memory!` warning that is shown to non-root users by granting `gpg` the `lock_memory` privilege using illumos' forced privileges feature.
```
build% id
uid=100(af) gid=1(other)
build% gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Go ahead and type your message ...
^Z
zsh: suspended  gpg
build% pfexec pcred `pgrep -n gpg`
244:    e/r/suid=100  e/r/sgid=1
build% pfexec ppriv `pgrep -n gpg`
244:    gpg
flags = <none>
E: basic,proc_lock_memory
I: basic
P: basic,proc_lock_memory
build% ls -lL =gpg
-rwsr-xr-x   1 root     bin        2.90M Dec 21 21:51 /opt/ooce/bin/gpg*
build% rg gnupg /etc/security/exec_attr
98:Forced Privilege:solaris:cmd:::/opt/ooce/gnupg/bin/gpg:privs=proc_lock_memory
```

gnupg: grant proc_lock_memory

---

lib/functions.sh

Now that pip supports the INSTALLER flag file, it is no longer necessary
to flatten python eggs.

Stop flattening python egg info

---

build/alpine/build.sh
build/alpine/patches/series
build/alpine/patches/uuid.patch

The current algorithm is flawed, using only the bottom bits of `random()`. From the man page:
> Different srandom() seeds often produce, within an offset, the same sequence of low order bits from random().

alpine: switch to libuuid for uuid generation

---

build/citus/build.sh
build/citus/files/ctf.ignore
build/citus/local.mog
build/citus/patches/fix-build-in-zone.patch
build/citus/patches/series
build/citus/patches/sys_stat.patch
build/postgresql/build-10.sh
build/postgresql/build-11.sh
build/postgresql/build-12.sh
build/postgresql/build-13.sh
build/postgresql/build-14.sh
build/postgresql/patches-12/dism.patch
build/postgresql/patches-12/series
build/postgresql/patches-13/dism.patch
build/postgresql/patches-13/series
build/postgresql/patches-14/dism.patch
build/postgresql/patches-14/series
doc/baseline
doc/packages.md
tools/audit

This adds support for using Intimate Shared Memory using the sysv SHM
methods and Dynamic Intimate Shared Memory when available by checking
for the SHM_PAGEABLE flag in <sys/shm.h>. This makes it possible to have
ISM/DISM without needing to set the shared_memory_type and
dynamic_shared_memory_type to sysv in postgresql.conf. The setting of
shared_memory_type is something that seems to origin from Joyent for
Manta and is available in upstream versions 12 and later so we only
patch those versions for now. Dropped --with-xslt configure options
as all versions issue an unrecognized option for that configure option.

postgresql use ISM by default and add DISM support.

---

build/postgresql/build-14.sh
build/postgresql/files/ctf.ignore

This statically links the llvm stuff into /opt/ooce/pgsql-14/lib/amd64/llvmjit.so which leads to
it being around 50 Mb e.g. pkg.csize=18194824 pkg.size=50894672
I first tried dynamic linking but the we need  /opt/ooce/llvm-13/lib/libLLVM-13.so which is 116967096 bytes.
So statically linking saves us about 56% thanks hadfl for the hint.

enable JIT/llvm support for postgresql14.

---

build/pg_repack/build.sh

This fixes published both pg13 and pg14 version under the same pkg name. The is a missing \ in the cmdline before make_package which I missed by last moment change.

pg_repack fix typo in build script.

---

build/dnsmasq/build.sh
build/dnsmasq/files/dnsmasq.xml
build/dnsmasq/local.mog
build/dnsmasq/patches/patch-src_bpf.c.patch
build/dnsmasq/patches/patch-src_dump.c.patch
build/dnsmasq/patches/series
doc/baseline
doc/idlist.md
doc/packages.md

Hello! This PR adds the `dnsmasq` package.
Possible Concerns
-------------------
This is my first PR for omnios-extra so it's possible I got things wrong or incorrect here.  A couple of possible concerns I had are:
I currently have this under the `network` category, but should it be under `ooce`? I'm not sure what the preference here is for that.  FWIW I based my implementation for this service off of the `mosquitto` package which uses the `network` category.
I basically arbitrarily picked a UID and GID that didn't seem to be in use (i used a simple `grep` over the `build/` directory) - is there a better way to pick a UID and GID that won't possibly conflict?
Notes
------
The patches were directly copied from Joyent/pkgsrc for SmartOS …

dnsmasq: add package (ver 2.86)

---

build/bwm-ng/build.sh
build/bwm-ng/local.mog
doc/baseline
doc/packages.md

a fairly straight forward package add, i've been using `bwm-ng` for about 15 years and it's pretty much muscle-memory for me at this point.  source https://github.com/vgropp/bwm-ng
Concerns
----------
I chose what i thought was the best name for this (`ooce/network/bwm-ng`) but if it better fits under another category i'm fine with changing it.
Testing
-------
```
$ sudo pkg install bwm-ng
$ bwm-ng -h
Bandwidth Monitor NG (bwm-ng) v0.6.3USAGE: bwm-ng [OPTION] ... [CONFIGFILE]
displays current ethernet interfaces stats
...
```

bwm-ng: add package (ver 0.6.3)

---

build/dnscrypt-proxy/build.sh
build/dnscrypt-proxy/files/dnscrypt-proxy.xml
build/dnscrypt-proxy/local.mog
doc/baseline
doc/idlist.md
doc/packages.md

Add [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy) at the latest version.
**NOTE:** This package works on my test setup but has 2 errors it encounters that I currently skip.
Errors
------
```
opt/ooce/bin/dnscrypt-proxy does not include stack smashing protection
```
This is a go binary built simply with `go build` - I personally am not very familiar with building go binaries so i'm not sure how to get this protection when compiling the binary.  Any insights on this would be appreciated.
This software is released under the [ISC License](https://en.wikipedia.org/wiki/ISC_license) which doesn't seem to be recognized in `doc/licences`.  It appears this license is similar to the BSD or MIT license, so I would imagine it wouldn't be a conflict to allow it in omnios-extra?
--- …

dnscrypt-proxy: add package (ver 2.1.1)

---

build/acltool/build.sh
build/buildctl
build/ffmpeg/build.sh
build/flamegraph/build.sh
build/mattermost/build.sh
build/ncdu/build.sh
build/omni/build.sh
build/pango/build.sh
build/tcpdump/build.sh
lib/functions.sh

This makes every package respond correctly to `./build.sh -x` and `./build.sh -xx`, and allow download and extraction of the whole source via `cd build; ./buildctl -xx build parallel 10` or similar.

Fixes to fully support extract mode (-x/-xx)

---

build/vaultwarden/build.sh

Upstream has renamed the numbering of the webvault.
Will soon upgrade to 2022.6.0 when that is merged.

vaultwarden: upgrade webvault version to 2022.5.2

---

build/tig/build.sh
build/tig/local.mog
doc/baseline
doc/packages.md

Running `build.sh` results in an `--- Comparing old package with new` error. Maybe I've done some mistake with adding to `doc/baseline`? I attempted to follow the instructions and mimicked earlier commits in the history (such as e.g. 1e8d76da).
There are also a bunch of these warnings when building on an up-to-date bloody:
>   .../omnios-extra/lib/functions.sh: line 193: /opt/onbld/bin/find_elf: No such file or directory
I'm posting as a draft PR for now. If anyone would be able to provide some insight in what I've missed, that would be most appreciated.

tig: add package (ver 2.5.5)

---

build/vaultwarden/build.sh

This bumps the vault warden web vault to the latest version that's being used with 1.25.1

Bump vaultwarden web vault to v2022.6.2

---

build/lsof/build.sh
build/lsof/patches/genunix.patch
build/lsof/patches/include_limits.patch
build/lsof/patches/series

As of `14768: retire nca`, the `sockfs` module no longer contains CTF data for the types that `lsof` needs. However, these are present in `genunix` and apparently always have been (at least back to r151038) so we can safely patch `lsof` to read those. 
```
r151038% ctfdump -c /kernel/amd64/genunix| grep sotpi
typedef struct sotpi_info sotpi_info_t;
struct sotpi_info { /* 0x140 bytes */
r151038% ctfdump -c /kernel/amd64/genunix| grep soaddr
struct soaddr { /* 0x10 bytes */
```

Retrieve CTF data from genunix instead of sockfs

---

build/ripgrep/build.sh

```diff
--- Comparing old package with new
+dir  path=opt/ooce/share owner=root group=bin mode=0755
+dir  path=opt/ooce/share/man owner=root group=bin mode=0755 facet.doc.man=true
+dir  path=opt/ooce/share/man/man1 owner=root group=bin mode=0755 facet.doc.man=true
+file path=opt/ooce/share/man/man1/rg.1 owner=root group=bin mode=0644 restart_fmri=svc:/system/update-man-index:default facet.doc.man=true
```

ripgrep: fix man page generation

---

build/wireguard-go/build.sh
build/wireguard-go/local.mog
build/wireguard-tools/build.sh
build/wireguard-tools/files/wg-quick.xml
build/wireguard-tools/local.mog
doc/baseline
doc/packages.md

I'd love to get these packages out into the illumos community to help get feedback and bug fixes for
WireGuard/wireguard-go#39 and WireGuard/wireguard-tools#17
These packages ship the code as it exists in those PRs today (tied to the specific commits).
Some notes for the original version of the SMF manifest can be found here:
https://github.com/nshalman/wireguard-tools/blob/wg-quick-for-sunos/contrib/smf/README.md

WireGuard packages (wireguard-go and wireguard-tools)

---

build/helix/build.sh
build/helix/files/hx
build/helix/local.mog
doc/baseline
doc/packages.md
lib/functions.sh

@hadfl / @citrus-it  this is what I pinged about over chat.
Some open issues here:
- I don't think I have `files/hx` setup properly to land in `/opt/ooce/bin/hx`
- The so files in the runtime dir shipped by helix get stripped (not sure if this matters?)
- I have an issue somewhere that's reporting "Manifest contains unresolved variables"
The idea though is that this binary should land in `/opt/ooce/helix/bin/hx` and the runtime lands in `/var/opt/occe/helix/runtime` and the wrapper script exports the proper variable to tell helix where the runtime lives.
This is what linux distros do.  An example of one such case is:
https://github.com/archlinux/svntogit-community/blob/packages/helix/trunk/helix.sh

First pass at helix pkg

---

build/clang/patches-13/add-rpath-for-libstdcxx.patch
build/clang/patches-14/add-rpath-for-libstdcxx.patch
build/clang/patches-15/add-rpath-for-libstdcxx.patch
build/clang/patches-16/add-rpath-for-libstdcxx.patch
build/hunspell/build.sh
tools/audit

when i did a test-build of `hunspell`  recently, @richlowe discovered, that the shared libraries are using the default libstdc++ library and not the ones we build against. investigating this revealed that libtool is adding `-nostdlib` which prevents setting the correct `RPATH` for libstdc++.
This change should make clang behave like our gcc does and therefore lead to least surprise to the user.

clang: relax check whether to add the RPATH for libstdc++

---

build/atuin/build.sh
build/atuin/local.mog
doc/baseline
doc/packages.md

This provides [atuin](https://atuin.sh) so that I can stop manually running `cargo install --locked atuin` everywhere.
Once this is in, I plan to update their [install script](https://github.com/atuinsh/atuin/blob/main/install.sh#L105) to use `pkg install atuin`.
I built this locally on r46.
Note that I locally use `MIRROR=https://foo..` in `lib/site.sh` providing the downloaded GitHub release tar and checksum digest on my fileserver.
I am not sure how to gate this on a particular Rust version as building with the rust in r40 was too old prompting me to update my development VM. It seems there is at least some cargo workspace feature being used that is not supported in older Rust releases.
Let me know if there's anything else I can do to help move this PR along.

Want atuin

---

build/vaultwarden/build.sh
doc/packages.md

Built on r46:
```
***
*** Differences found between old and new packages
***
Do you wish to continue anyway? (y/n) y
===== User elected to continue after prompt. =====
-- Cleaning up
--- Removing temporary install directory /var/tmp/build_link/vaultwarden-1.29.1/ooce_application_vaultwarden_pkg
--- Cleaning up temporary manifest and transform files
Done.
Time: ooce/application/vaultwarden - 0h15m22s
```

Bump vaultwarden to 1.29.1 and webvault to 2023.7.1

---

build/meta/extra-build-tools.p5m
build/pg_extension/common.sh
build/postgresql/build-16.sh
build/postgresql/files/ctf.ignore
build/postgresql/patches-16/dism.patch
build/postgresql/patches-16/pam_conv.patch
build/postgresql/patches-16/series
doc/baseline
doc/packages.md

This mostly works I only have one problem and that is that the RPATH is missing /opt/ooce/lib/amd64 and as such is not finding the icu shared libs. If I fix the RPATH and add the path I can run initdb and start a database. I also added the extensions but
have not build them yet and citus might not have support for pgsql16 given it was released yesterday. I can drop the extensions
build for now and we can add that the next time some extension gets updated.

Add postgresql 16

---

build/postgresql/build-14.sh
build/postgresql/build-15.sh
build/postgresql/build-16.sh

LLVMBuildLoad symbol is deprecated and unavailable in clang16 and later. Until postgresql starts supporting newer llvm versions we need to set the maximum clang version that still supports LLVMBuildLoad.

Build postgresql version with clang15

---

build/bazel/build.sh
build/bazel/local.mog
build/bazel/patches/illumos.patch
build/bazel/patches/omnios.patch
build/bazel/patches/series
doc/baseline
doc/packages.md
tools/audit

This change adds a new package - `ooce/developer/bazel` based on the work by @siepkes in https://github.com/siepkes/bazel-smartos
I have run through Bazel's getting started guide using this package and that was successful:
```
build% bazel build //main:hello-world
Starting local Bazel server and connecting to it...
INFO: Analyzed target //main:hello-world (38 packages loaded, 157 targets configured).
INFO: Found 1 target...
Target //main:hello-world up-to-date:
bazel-bin/main/hello-world
INFO: Elapsed time: 10.333s, Critical Path: 0.67s
INFO: 5 processes: 3 internal, 2 processwrapper-sandbox.
INFO: Build completed successfully, 5 total actions
build% ./bazel-bin/main/hello-world
Hello world
Wed Jan  3 19:41:53 2024
```

Add bazel 6.3.2

---

build/x11/libxcb/build.sh
lib/config.sh

I successfully ran a full omnios-extra build on the latest bloody with this change.

Switch omnios-extra to Python 3.12

---

build/apache/build-24.sh
build/apache/local.mog
build/caddy/build.sh
build/caddy/files/caddy-template.xml
build/caddy/local.mog
build/caddy/patches/0001-Switch-Solaris-derivatives-away-from-listen_unix.patch
build/caddy/patches/series
build/webservd/webservd.p5m
doc/baseline
doc/packages.md

Add v2.7.6 of the Caddy web server.
Add patch to fix Solaris-derivative build.
Comes from caddy master:76611fa15079b755ddf3c859ae2ea0ad2123223f and this PR 6021: https://github.com/caddyserver/caddy/pull/6021

caddy: add version 2.7.6 to extra.omnios

---

build/rlwrap/build.sh
build/tailscale/build.sh
build/tig/build.sh
build/wireguard-go/build.sh

This change adds a few missing `patch_source` calls to packages that
are needed so that they don't build when run with `-x` (extract source
only). Even if there are currently no patches, all packages should
call this function.

Add missing patch_source calls

---

build/neovim/patches/illumos-support.patch
build/neovim/patches/series
build/neovim/patches/use-system-default-tty-modes.patch

A few fixes for `:terminal` support in Neovim 0.10:
* The **openpty(3C)** compatibility shim is not quite right in one critical respect: pushing a STREAMS module onto a tty device can have the side effect of making that device the process's controlling terminal.  Using `__I_PUSH_NOCTTY` avoids that side effect.  This was causing the **nvim --embed** child process to exit unexpectedly when `:terminal` was used.
* Neovim presently does some partially incorrect and wholly ill-advised construction of a **struct termios** object from whole cloth when starting an interactive child process.  This likely has a subtle impact even on Linux (I verified that it is not _quite_ producing a default object there either, though the differences are less severe).  The delta between _our_ system default …

terminal handling fixes for Neovim 0.10

---

build/helix/local.mog

Omit the grammar sources from the Helix package. This removes the better part of 20,000 small files from the package, none of which are not required to run Helix. 
[Homebrew already do this](https://github.com/helix-editor/helix/issues/3437) and it is [recommended by the Helix devs](https://github.com/helix-editor/helix/issues/6187#issuecomment-1769860105).

dont-package-helix-grammar-sources

---

build/oath-toolkit/build.sh
lib/mog/global-transforms.mog

```diff
-file path=opt/ooce/lib/amd64/liboath.a owner=root group=bin mode=0644 facet.devel=true
-file path=opt/ooce/lib/amd64/libpskc.a owner=root group=bin mode=0644 facet.devel=true
+link path=opt/ooce/lib/liboath.so target=liboath.so.0.1.3
+link path=opt/ooce/lib/liboath.so.0 target=liboath.so.0.1.3
+file path=opt/ooce/lib/liboath.so.0.1.3 owner=root group=bin mode=0755 elfarch=i386 elfbits=32
+link path=opt/ooce/lib/libpskc.so target=libpskc.so.0.0.1
+link path=opt/ooce/lib/libpskc.so.0 target=libpskc.so.0.0.1
+file path=opt/ooce/lib/libpskc.so.0.0.1 owner=root group=bin mode=0755 elfarch=i386 elfbits=32
+dir  path=opt/ooce/lib/pkgconfig owner=root group=other mode=0755 facet.devel=true
+file path=opt/ooce/lib/pkgconfig/liboath.pc owner=root group=bin mode=0644 facet.devel=true
+file …
```

oath-toolkit: ship 32-bit too, drop static libraries

---

build/helix/build.sh
doc/packages.md

I built this version for myself and I've been using it for a couple of days with no issues. The version is year-month, so it's [a more significant upgrade than the numbers might suggest](https://github.com/helix-editor/helix/blob/master/CHANGELOG.md#2407-2024-07-14).

bump Helix to 24.07

---

build/freeradius/build.sh
build/freeradius/local.mog

fixes https://github.com/omniosorg/omnios-extra/issues/1494

freeradius: revert to use shared libtalloc

---

build/neovim/build.sh
build/neovim/patches/illumos-support.patch
build/neovim/patches/libuv.patch
build/neovim/patches/path.patch
build/neovim/patches/series
build/neovim/patches/use-system-default-tty-modes.patch
doc/packages.md

Before this change:
```
nvim --clean
:lua print(package.path)
./?.lua;/temp/build_hadfl/neovim-0.10.0/neovim-0.10.0/.deps/usr/share/luajit-2.1
/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/temp/
build_hadfl/neovim-0.10.0/neovim-0.10.0/.deps/usr/share/lua/5.1/?.lua;/temp/buil
d_hadfl/neovim-0.10.0/neovim-0.10.0/.deps/usr/share/lua/5.1/?/init.lua
:lua print(package.cpath)
./?.so;/usr/local/lib/lua/5.1/?.so;/temp/build_hadfl/neovim-0.10.0/neovim-0.10.0
/.deps/usr/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
:q
```
and after, the build paths are no longer included:
```
nvim --clean
:lua print(package.path)
./?.lua;/opt/ooce/share/luajit-2.1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/loc
al/share/lua/5.1/?/init.lua;/opt/ooce/share/lua/5.1/?.lua;/opt/ooce/share/ …
```

neovim: update to 0.10.1 and fix lua package.{path,cpath}

---

build/aarch64/gcc10/local.mog
build/clang/build-18.sh
build/clang/local.mog
build/llvm/patches-18/aarch64-eh_frame-ro.patch
build/llvm/patches-18/series

When I was doing first test builds of clang 19, I realised that the configure option `GCC_INSTALL_PREFIX` is deprecated. Apparently it also interferes with the `--sysroot` command line option.
Instead, we are now shipping default configurations for all supported triplets on OmniOS so clang will find the runtime objects and libstdc++ headers from gcc it uses (users can still easily override them but we provide working defaults). This also makes cross compiling for aarch64 with clang 18 work.
This is the deprecation warning:
```
GCC_INSTALL_PREFIX is deprecated and will be removed.  Use configuration
files (https://clang.llvm.org/docs/UsersManual.html#configuration-files)to
specify the default --gcc-install-dir= or --gcc-triple=.  --gcc-toolchain=
is discouraged.  See …
```

clang 18 should be able to cross compile for aarch64

---

build/victoriametrics/build.sh
build/victoriametrics/files/README.install
build/victoriametrics/files/victoria-metrics-profile-template.xml
build/victoriametrics/files/victoriametrics-template.xml
build/victoriametrics/files/vmagent-profile.xml
build/victoriametrics/local.mog
doc/baseline
doc/idlist.md
doc/packages.md
lib/functions.sh

Package multiple pieces of the Prometheus compatible VictoriaMetrics suite:
- victoria-metrics
- vmagent
- vmbackup
- vmrestore
- vmctl
Whilst here, correct a minor spelling error in functions.sh.

Add VictoriaMetrics package, a time series database.

---

build/vaultwarden/build.sh
doc/packages.md

Version 1.32.5 addresses a CVE so we should bump to the latest patch release.
https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.5
I don't have a build VM setup at the moment if someone could test this for me before merging that would be appreciated!

Bump vaultwarden due to CVE

---

build/victoriametrics/build.sh
doc/packages.md

Update VictoriaMetrics to recent 1.102.8 LTS.

Update to VictoriaMetrics 1.102.8.

---

build/vaultwarden/build.sh
doc/packages.md

Been wondering why push was broken, it's fixed in this update.
https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.6
I'm traveling at the moment so haven't given this a build in a VM yet. But past updates seemed to have went fine without issue.

bump vaultwarden to 1.32.6

---

build/vaultwarden/build.sh
doc/packages.md

Seems another security related release.
> Security Fixes
>
> We have yet a few other security fixes for this release. We discovered that groups were able to be edited by any admin from any organization because the organization was not validated or used within the query. This could potentially allow an admin from other organizations to modify, or delete groups from any organization if they know the uuid of the group.
> We suggest people to update a.s.a.p. to mitigate this risk.
-- https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.7
Haven't given this a build in a VM as it seems my build zone is broken. But past updates seemed to have went fine without issue.

bump vaultwarden to 1.32.7

---

build/helix/build.sh
doc/packages.md

There's a new version of helix with a bunch of nice features.
Builds successfully:
```
Do you wish to continue anyway? (y/n) y
===== User elected to continue after prompt. =====
-- Cleaning up
--- Removing temporary install directory /tmp/build_omnios/helix-25.01/ooce_editor_helix_pkg
--- Cleaning up temporary manifest and transform files
Done.
Time: ooce/editor/helix - 0h4m40s
```
Note I pulled the source tar.xz and used site.sh to point the build system at it since I can't modify the omnios mirror web server.

Bump helix to version 25.01

---

build/starship/build.sh
build/starship/local.mog
build/starship/patches/do-not-strip-symbol-table.patch
build/starship/patches/series
doc/baseline
doc/packages.md

This adds the starship prompt package https://starship.rs
I have been compiling this and distributing to hosts/zones manually but it would be nice to have in pkg.
The pkg successfully builds on my build box but complains about ELF runtimes and stack smashing which I think are safe to ignore iirc?

Add starship shell prompt

---

build/neovim/build.sh
build/neovim/patches/illumos-luajit-umem-workaround.patch
build/neovim/patches/series
doc/packages.md

This change updates Neovim to 0.10.3, which includes a relatively crucial LSP bug fix around server cancellation.  It also adds a temporary workaround for #1539, until we can find time to fix the real issues there.
I have built and tested this on an OmniOS r151046 LTS system, and it appears to work.  I ran ":checkhealth" and also the plugin checks for the Lazy plugin system, and there were no weird new problems.  I also edited a text file and made use of the RPC socket.

neovim: update to 0.10.3, work around #1539

---

README.md
lib/functions.sh

Although those working on package updates are able to change the download mirror in `lib/site.sh` or via `set_mirror` directives in the build script, it would be useful if they could do this transiently via a new flag to `build.sh` and not have to make changes that then need to be reverted.
This adds a new `-M` option to `build.sh` that does this, and updates the documentation accordingly.

Add -M build flag to temporarily override mirror for development

---

lib/config.sh

Following "17091 Use DWARFv4 by default" in gate, let us do the same in extra

Use DWARFv4 by default with gcc14

---

build/vaultwarden/build.sh
doc/packages.md

https://github.com/dani-garcia/vaultwarden/releases/tag/1.33.2
Mostly for CVE-2025-24898

vaultwarden 1.33.2

---

build/caddy/files/caddy-template.xml

I noticed on one of my caddy instances that it was running with expired certs even though I had called its SMF refresh method.  It turns out caddy won't reload the config if nothing has changed.
```
--force will cause a reload to happen even if the specified config is the same as what Caddy is already running.
Can be useful to force Caddy to reprovision its modules, which can have side-effects, for example:
reloading manually-loaded TLS certificates.
```

Add --force to caddy refresh method
